<?php
  /***************************************************************************************/
  // Add all functions generated by manage gamify application / badge section for manually trigger within your application.
  //**************************************************************************************/
  if(!defined("INCLUDE_ROOT"))
   include_once("../../include/config.php");
  
  include_once(INCLUDE_ROOT . "bll/ga_core_bll.php");
  class ga_badge_item_events {
	  
	// <summary>
	// The Network Slot (Reward)
	// </summary>
	function trigger_item_17($userid)
	{
		$obj = new ga_core_bll();
		$obj->trigger_item($userid, 17);
	}
	
  }

?>